apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mysql
        image: mysql:9.4.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: secretpass
        - name: MYSQL_DATABASE
          value: myapp
        ports:
        - containerPort: 3306