= Certified Kubernetes Administrator (CKA) Study Guide, 2nd Edition

++++
<br>
<img align="left" role="left" src="https://learning.oreilly.com/library/cover/9781098107215/" width="110" alt="Book Cover" />
++++
Source code for book https://www.oreilly.com/library/view/certified-kubernetes-administrator/9781098107215/["Certified Kubernetes Administrator (CKA) Study Guide, 2nd Edition"], In-Depth Guidance and Practice, published by Benjamin Muschko for O'Reilly Media Inc.

This study guide walks you through all the topics you need to fully prepare for the exam covering Kubernetes 1.32. Author Benjamin Muschko also shares his personal experience with preparing for all aspects of the exam.

> **_NOTE:_** The source code for the 1st edition of the book is available https://github.com/bmuschko/cka-study-guide/tree/1st-edition[here].

== Source Code by Chapters

. Introduction
* Exam Details and Resources
* Kubernetes in a Nutshell
* link:./ch03[Interacting with Kubernetes]
. Cluster Architecture, Installation and Configuration
* link:./ch04[Cluster Installation and Upgrade]
* link:./ch05[Backing Up and Restoring etcd]
* link:./ch06[Authentication, Authorization, and Admission Control]
* link:./ch07[Operators and Custom Resource Definitions (CRDs)]
* link:./ch08[Helm and Kustomize]
. Workloads and Scheduling
* link:./ch09[Deployments]
* link:./ch10[ConfigMaps and Secrets]