apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  tolerations:
  - key: "special"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: nginx 
    image: nginx:1.27.1