apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: metrics
    port: 9090
    targetPort: 9090