apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    team: alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-beta
  labels:
    team: beta
---
apiVersion: v1
kind: Pod
metadata:
  name: alpha-app
  namespace: team-alpha
  labels:
    app: alpha-app
    team: alpha
spec:
  containers:
  - name: app
    image: alpine/curl:8.14.1
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo 'Alpha app running'; sleep 3600; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: beta-app
  namespace: team-beta
  labels:
    app: beta-app
    team: beta
spec:
  containers:
  - name: app
    image: nginx:1.27.3-alpine
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: beta-app
  namespace: team-beta
spec:
  selector:
    app: beta-app
    team: beta
  ports:
  - port: 8080
    targetPort: 80