BOX_IMAGE = "ubuntu/bionic64"
WORKER_COUNT = 3
POD_CIDR = "172.18.0.0/16"
API_ADV_ADDRESS = "192.168.56.10"
K8S_VERSION = "1.29.10-1.1"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "k8s-control-plane" do |node|
    node.vm.hostname = "k8s-control-plane"
    node.vm.network :private_network, ip: "192.168.56.10"
    node.vm.provider :virtualbox do |vb|
      vb.name = "k8s-control-plane"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision "shell", path: "common.sh", args: "#{K8S_VERSION}"
    node.vm.provision "shell", path: "control-plane.sh", args: "#{POD_CIDR} #{API_ADV_ADDRESS}"
  end

  (1..WORKER_COUNT).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.hostname = "worker-#{i}"
      node.vm.network :private_network, ip: "192.168.56.#{i + 20}"
      node.vm.provider :virtualbox do |vb|
        vb.name = "worker-#{i}"
        vb.memory = 1024
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "common.sh", args: "#{K8S_VERSION}"
      node.vm.provision "shell", path: "worker.sh", args: "#{i}"
    end
  end

  config.vm.provision "shell",
    run: "always",
    inline: "swapoff -a"
end
