BOX_IMAGE = "ubuntu/bionic64"
WORKER_COUNT = 3
POD_CIDR = "172.18.0.0/16"
API_ADV_ADDRESS = "10.8.8.10"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_IMAGE

  config.vm.define "k8s-master" do |node|
    node.vm.hostname = "k8s-master"
    node.vm.network :private_network, ip: "10.8.8.10"
    node.vm.provider :virtualbox do |vb|
      vb.name = "k8s-master"
      vb.memory = 2048
      vb.cpus = 2
    end
    node.vm.provision "shell", path: "common.sh"
    node.vm.provision "shell", path: "master.sh", args: "#{POD_CIDR} #{API_ADV_ADDRESS}"
  end

  (1..WORKER_COUNT).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.hostname = "worker-#{i}"
      node.vm.network :private_network, ip: "10.8.8.#{i + 20}"
      node.vm.provider :virtualbox do |vb|
        vb.name = "worker-#{i}"
        vb.memory = 1024
        vb.cpus = 2
      end
      node.vm.provision "shell", path: "common.sh"
      node.vm.provision "shell", path: "worker.sh", args: "#{i}"
    end
  end

  config.vm.provision "shell",
    run: "always",
    inline: "swapoff -a"
end
