apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: default
spec:
  gatewayClassName: nginx  # or your specific GatewayClass name
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: example.local