apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-app-service
  name: web-app-service
spec:
  ports:
  - name: web-app-port
    port: {{ .Values.service_port }}
    protocol: TCP
    targetPort: 3000
  selector:
    app: web-app
  type: NodePort
