apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: test-container
    image: busybox:1.36.1
    command: ["/bin/sh", "-c", "env"]
    volumeMounts:
    - mountPath: /tmp/secret
      name: mysecret
  volumes:
  - name: mysecret
    secret:
      secretName: mysecret