name: Validate Manifests
on:
  pull_request:
  push:
    branches: 
      - master
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  build:
    name: Validate Manifests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1
      - name: Validate Against Kubernetes Schema
        run: kubeconform -kubernetes-version=1.33.3 -ignore-filename-pattern=.github/workflows -ignore-filename-pattern=.json$ -ignore-filename-pattern=kustomize -ignore-filename-pattern=helm -ignore-filename-pattern=ch07/argo-cd -ignore-filename-pattern=ch19 -ignore-filename-pattern=app-a/ch07 -ignore-filename-pattern=app-a/ch19 -summary .