apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-db
  name: mysql-db
spec:
  containers:
  - image: mysql:8.1.0
    name: mysql-db
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
      protocol: TCP
